// Từ điển Việt → Anh chuyên ngành nội thất / hoàn thiện / FF&E / MEP khách sạn (dùng cho bộ dịch tự động, không AI).
// Dạng: thẻ|cụm tiếng Việt|tiếng Anh (viết thường, có dấu). Thẻ:
//  N = danh từ chính (đứng cuối trong tiếng Anh)   M = vật liệu (đứng trước danh từ)   C = màu (đứng đầu cụm)
//  A = tính từ / kiểu / cách lắp (đứng trước danh từ, theo thứ tự đảo)   Y = loại / công dụng (sát danh từ, giữ thứ tự)
//  P = giới từ mở cụm mới   T = cụm cuối câu giữ nguyên vị trí   K = từ bỏ (màu, bằng, loại…)
export type Tag = 'N' | 'M' | 'C' | 'A' | 'Y' | 'P' | 'T' | 'K'
export type Gloss = { tag: Tag; en: string }

const RAW = `
N|sàn|flooring;N|tường|wall;N|trần|ceiling;N|vách|partition;N|vách ngăn|partition;N|vách ốp|wall panelling;N|ốp tường|wall cladding;N|ốp vách|wall cladding;N|len chân tường|skirting board;N|phào chỉ|cornice;N|cột|column;N|dầm|beam;N|cửa|door;N|cửa sổ|window;N|cánh cửa|door leaf;N|khuôn cửa|door frame;N|khung cửa|door frame;N|nẹp cửa|door trim;N|cửa kính|glass door;N|vách kính|glass partition;N|cửa thép chống cháy|fire-rated steel door;N|cửa gió|air grille;N|miệng gió|air diffuser;N|miệng gió hồi|return air grille;N|nắp thăm trần|ceiling access panel;N|nắp thoát sàn|floor drain cover;N|ga thoát sàn|floor drain;N|thoát sàn|floor drain;N|nẹp|trim;N|nẹp chuyển tiếp|transition strip;N|bậc thang|stair step;N|tay vịn|handrail;N|lan can|balustrade;N|rèm|curtain;N|rèm cuốn|roller blind;N|rèm sáo|venetian blind;N|rèm vải|fabric curtain;N|thảm|carpet;N|thảm trải sàn|carpet;N|tranh|artwork;N|tranh treo tường|wall art;N|tranh in canvas|canvas print;N|cây xanh|plants;N|cây|plant;N|chậu cây|planter;N|gương|mirror;N|gương soi|mirror;N|kệ|shelf;N|kệ sách|bookshelf;N|đợt kệ|shelf;N|tủ|cabinet;N|tủ quần áo|wardrobe;N|tủ tài liệu|filing cabinet;N|tủ locker|locker;N|tủ lavabo|vanity unit;N|tủ phụ|credenza;N|tủ bếp|kitchen cabinet;N|tủ buffet|buffet unit;N|hộc tủ|pedestal;N|ngăn kéo|drawer;N|bàn|table;N|bàn ăn|dining table;N|bàn họp|meeting table;N|bàn làm việc|desk;N|bàn trà|coffee table;N|bàn tròn|round table;N|bàn chậu rửa|sink counter;N|bàn xếp đồ|folding table;N|bàn cầu|water closet;N|ghế|chair;N|ghế ăn|dining chair;N|ghế xoay|swivel chair;N|ghế tiếp khách|visitor chair;N|ghế giám đốc|executive chair;N|ghế đẩu|stool;N|sofa|sofa;N|đôn|ottoman;N|đôn băng|bench;N|băng ghế|bench;N|giường|bed;N|đầu giường|headboard;N|quầy|counter;N|quầy lễ tân|reception counter;N|quầy tiếp tân|reception counter;N|quầy bar|bar counter;N|giá treo|rack;N|giá treo quần áo|garment rack;N|giá treo tv|TV bracket;N|xe đẩy|trolley;N|kho|storage room;N|kệ kho|storage rack;
N|đèn|light;N|đèn thả|pendant light;N|đèn thả trần|pendant light;N|đèn led thả trần|LED pendant light;N|đèn led hộp thả trần|LED box pendant light;N|viền|edging;N|khung viền|frame edging;N|ngồi|seat;N|đèn downlight|downlight;N|đèn led|LED light;N|đèn ống bơ|spotlight;N|đèn tường|wall light;N|đèn bàn|table lamp;N|đèn sàn|floor lamp;N|đèn chùm|chandelier;N|đèn thanh|linear light;N|đèn dây|led strip light;N|đèn hắt|cove light;N|đèn exit|exit sign;N|đèn sự cố|emergency light;N|công tắc|switch;N|ổ cắm|socket;N|đầu báo khói|smoke detector;N|sprinkler|sprinkler;N|loa|speaker;N|camera|camera;N|dàn lạnh|fan coil unit;N|dàn lạnh cassette|cassette fan coil unit;N|quạt hút mùi|exhaust fan;N|máy sấy tay|hand dryer;N|máy giặt|washing machine;N|máy sấy|dryer;N|máy in|printer;N|tivi|TV;N|màn hình|monitor;N|máy tính|computer;N|máy chiếu|projector;N|bình chữa cháy|fire extinguisher;N|đầu chờ|stub-out;N|mặt nạ|cover plate;N|mặt nạ dàn lạnh|fan coil cover;
N|chậu rửa|washbasin;N|lavabo|washbasin;N|vòi nước|tap;N|vòi rửa|basin mixer;N|vòi xịt|bidet spray;N|vòi|tap;N|sen tắm|shower;N|sen cây|shower column;N|bồn tiểu|urinal;N|bồn tiểu nam|male urinal;N|bồn cầu|water closet;N|bồn tắm|bathtub;N|hộp đựng giấy|tissue holder;N|hộp đựng xà phòng|soap dispenser;N|thùng rác|waste bin;N|van khóa|isolation valve;N|van khóa chữ t|t-handle angle valve;N|phụ kiện|accessories;N|bản lề|hinge;N|bản lề lá|butt hinge;N|bản lề âm|concealed hinge;N|tay nắm|handle;N|tay nắm cửa|door handle;N|khóa|lock;N|khóa tủ|cabinet lock;N|chặn cửa|door stop;N|ray trượt|drawer slide;N|chân bàn|table leg;N|chân|leg;N|chân trụ|pedestal base;N|khung|frame;N|khung chân bàn|table base frame;N|mặt bàn|tabletop;N|mặt|top;N|mặt tủ|cabinet top;N|mặt đá|stone top;N|thùng|carcass;N|thùng cánh|carcass and doors;N|cánh|door;N|nệm|cushion;N|yếm bàn|modesty panel;N|decal|decal;N|logo|logo;
M|gỗ|wood;M|gỗ sồi|oak;M|gỗ công nghiệp|engineered wood;M|gỗ cn|engineered wood;M|gỗ tự nhiên|solid wood;M|gỗ keo|acacia wood;M|gỗ ghép|finger-jointed wood;M|mdf|MDF;M|mfc|MFC;M|hdf|HDF;M|plywood|plywood;M|ván ép|plywood;M|melamine|melamine;M|melamin|melamine;M|laminate|laminate;M|veneer|veneer;M|kính|glass;M|kính cường lực|tempered glass;M|kính dán|laminated glass;M|kính mờ|frosted glass;M|đá|stone;M|đá marble|marble;M|marble|marble;M|đá granite|granite;M|granite|granite;M|đá nhân tạo|engineered stone;M|đá nung kết|sintered stone;M|travertine|travertine;M|terrazzo|terrazzo;M|gạch|tile;M|gạch ceramic|ceramic tile;M|gạch porcelain|porcelain tile;M|gạch lát sàn|floor tile;M|gạch ốp tường|wall tile;M|gạch nhựa|vinyl tile;M|gạch thẻ|brick-slip tile;M|ceramic|ceramic;M|gốm|ceramic;M|sứ|porcelain;M|bê tông|concrete;M|bê tông mài|polished concrete;M|xi măng|cement;M|epoxy|epoxy;M|vinyl|vinyl;M|lvt|LVT;M|spc|SPC;M|pvc|PVC;M|nhựa|plastic;M|nhựa abs|ABS plastic;M|nhựa giả gỗ|wood-look plastic;M|mika|acrylic;M|acrylic|acrylic;M|nhôm|aluminium;M|hợp kim nhôm|aluminium alloy;M|thép|steel;M|thép hộp|steel box section;M|thép tấm|steel plate;M|sắt|iron;M|sắt tấm|steel plate;M|inox|stainless steel;M|inox 304|stainless steel 304;M|kim loại|metal;M|đồng|brass;M|đồng thau|brass;M|crôm|chrome;M|chrome|chrome;M|mạ crôm|chrome-plated;M|vải|fabric;M|vải bọc|upholstery fabric;M|vải dệt thô|coarse-woven fabric;M|nỉ|felt;M|da|leather;M|da simili|faux leather;M|simili|faux leather;M|polyester|polyester;M|lưới|mesh;M|mây|rattan;M|thạch cao|gypsum board;M|tấm thạch cao|gypsum board;M|gyproc|gypsum board;M|tiêu âm|acoustic;M|sơn|paint;M|sơn nước|emulsion paint;M|sơn tĩnh điện|powder-coated;M|sơn lót|primer;M|sơn hoàn thiện|finish paint;M|sơn dầu|oil paint;M|sơn epoxy|epoxy paint;M|nickel|nickel;M|cr/ni|Cr/Ni;
C|trắng|white;C|đen|black;C|xám|grey;C|ghi|grey;C|xám đậm|dark grey;C|xám nhạt|light grey;C|xám than|charcoal;C|xám ghi|grey;C|nâu|brown;C|nâu đỏ|reddish brown;C|đỏ|red;C|đỏ gạch|brick red;C|cam|orange;C|cam đất|terracotta;C|cam đào|peach;C|vàng|yellow;C|vàng mù tạt|mustard yellow;C|xanh|blue;C|xanh dương|blue;C|xanh lá|green;C|xanh lá sage|sage green;C|xanh pastel|pastel blue;C|be|beige;C|kem|cream;C|sồi|oak;C|sồi sáng|light oak;C|sồi nhạt|light oak;C|vân sồi|oak-grain;C|vân sồi sáng|light oak-grain;C|vân sồi nhạt|light oak-grain;C|vân gỗ|wood-grain;C|vân đá|stone-effect;C|vân mây|cloud-veined;C|tím|purple;C|hồng|pink;C|bạc|silver;C|vàng đồng|bronze;C|màu tối|dark;C|tối màu|dark-coloured;C|trong suốt|clear;C|trung tính|neutral white;C|đậm|dark;C|nhạt|light;C|sáng|light;C|ấm|warm;
A|tròn|round;A|bầu dục|oval;A|oval|oval;A|vuông|square;A|chữ nhật|rectangular;A|bo tròn|rounded;A|bo góc|rounded-corner;A|bo cong|curved;A|uốn cong|curved;A|cong|curved;A|lượn sóng|wavy;A|thấp|low;A|cao|tall;A|dài|long;A|ngắn|short;A|mỏng|thin;A|dày|thick;A|rộng|wide;A|lớn|large;A|nhỏ|small;A|mảnh|slim;A|phẳng|flat;A|trơn|plain;A|nổi|raised;A|âm|recessed;A|âm trần|recessed ceiling;A|âm tường|recessed wall;A|nổi trần|surface-mounted;A|gắn trần|ceiling-mounted;A|gắn tường|wall-mounted;A|treo tường|wall-mounted;A|gắn sàn|floor-mounted;A|âm sàn|in-floor;A|thả trần|suspended;A|treo trần|suspended;A|di động|mobile;A|xoay|swivel;A|gấp|folding;A|chống cháy|fire-rated;A|chống ẩm|moisture-resistant;A|chống nước|waterproof;A|chống trơn|anti-slip;A|chống trơn trượt|anti-slip;A|chống bám bẩn|stain-resistant;A|chống mài mòn|abrasion-resistant;A|chống xước|scratch-resistant;A|chống va đập|impact-resistant;A|chống nắng|sun-shading;A|cách nhiệt|heat-insulating;A|cách âm|sound-insulating;A|nhân tạo|artificial;A|tự nhiên|natural;A|trang trí|decorative;A|điểm nhấn|accent;A|nhấn|accent;A|hiện đại|modern;A|cao cấp|premium;A|công nghiệp|industrial;A|tiêu chuẩn|standard;A|mờ|matt;A|bóng|glossy;A|nhám|textured;A|mịn|smooth;A|liền mạch|seamless;A|đôi|double;A|đơn|single;A|nam|male;A|nữ|female;A|nhân viên|staff;A|khách|guest;A|lãnh đạo|executive;A|giám đốc|executive;A|văn phòng|office;A|tiếp khách|visitor;A|phục vụ|service;A|thông minh|smart;A|điện tử|electronic;A|mạ|plated;A|kịch trần|floor-to-ceiling;A|tự phục vụ|self-service;A|chịu lực|load-bearing;A|chịu tải nặng|heavy-duty;A|nhiều tầng|multi-tier;A|2 tầng|two-tier;A|3 tầng|three-tier;A|nam nữ|unisex;
Y|led|LED;Y|downlight|downlight;Y|spotlight|spotlight;Y|trang trí|decorative;Y|ăn uống|dining;Y|họp|meeting;Y|làm việc|work;Y|thay đồ|changing;Y|tài liệu|document;Y|hồ sơ|file;Y|điều hòa|air-conditioning;Y|vệ sinh|sanitary;Y|rửa tay|hand wash;Y|phòng tắm|bathroom;
P|có|with;P|kèm|with;P|kèm theo|with;P|với|with;P|tích hợp|with integrated;P|cho|for;P|dùng cho|for;P|để|for;P|theo|per;P|tại|at;P|ở|at;P|trong|in;P|ngoài|outside;P|giữa|between;P|trên|on;P|dưới|under;P|cùng|together with;P|như|as;
T|hoặc tương đương|or equivalent;T|màu nhấn|in accent colour;T|có bánh xe|on wheels;T|có bánh|on wheels;T|(hoặc tương đương)|(or equivalent);T|theo thiết kế|as per design;T|như thiết kế|as per design;T|theo chỉ định|as specified;T|phối hợp mep|coordinated with mep;T|phối hợp|coordinated;T|tham khảo|for reference;
K|màu|;K|bằng|;K|loại|;K|kiểu|;K|dạng|;K|hình|;K|thành|;K|làm|;K|từ|;K|các|;K|những|;K|một|;K|chất liệu|;
`
// Tên phòng / khu vực thường gặp (cả cụm → bản dịch cố định, viết hoa chữ đầu mỗi từ)
const ROOMS = `
hành lang|corridor;sảnh thang|lift lobby;sảnh|lobby;phòng họp|meeting room;phòng phỏng vấn|interview room;phòng thay đồ nam|male locker room;phòng thay đồ nữ|female locker room;phòng thay đồ|locker room;phòng giặt|laundry room;phòng đồng phục|uniform room;phòng cắm hoa|flower arranging room;phòng sơ cứu|first aid room;phòng an ninh|security room;phòng buồng phòng|housekeeping room;phòng cntt|IT room;phòng vệ sinh dụng cụ|janitor room;phòng tiệc|banquet room;phòng bếp|kitchen;các phòng bếp|kitchens;bếp|kitchen;nhà ăn nhân viên|staff canteen;căng tin|canteen;khu rửa bát đĩa|dishwashing area;khu rửa bát đĩa căng tin|canteen dishwashing area;khu sơ chế thô|rough prep area;khu rác ướt và rác khô|wet and dry waste area;khu nhập hàng|receiving area;khu kỹ thuật|technical area;khu văn phòng|office area;văn phòng chung|shared office;văn phòng nhận hàng|receiving office;văn phòng|office;kho hàng chung|general storage;kho hóa chất|chemical store;kho mát thực phẩm|chilled food store;kho phòng tiệc|banquet store;kho rượu|wine store;kho vải bẩn|soiled linen store;kho vải sạch|clean linen store;vệ sinh|toilet;nhà vệ sinh|toilet;pantry phục vụ ăn uống|dining pantry;pantry|pantry;thang máy|lift;thang bộ|staircase;tổng giám đốc|general manager;giám đốc điều hành|executive director;bộ phận hcns|hr department;bộ phận tài chính|finance department;bộ phận|department;tất cả các khu vực|all areas
`
export const GLOSS = new Map<string, Gloss>()
export const ROOM_GLOSS = new Map<string, string>()
for (const row of RAW.split(/;\s*\n?|\n/)) {
  const [t, vi, en] = row.trim().split('|')
  if (!t || vi == null || en == null) continue
  GLOSS.set(vi.trim().toLowerCase(), { tag: t as Tag, en: en.trim() })
}
for (const row of ROOMS.split(/;\s*\n?|\n/)) {
  const [vi, en] = row.trim().split('|')
  if (vi && en) ROOM_GLOSS.set(vi.trim().toLowerCase(), en.trim())
}
export const MAX_PHRASE = Math.max(...[...GLOSS.keys(), ...ROOM_GLOSS.keys()].map(k => k.split(' ').length))

/** Nhãn khoá của dòng thông số “Tên: giá trị” */
export const SPEC_KEYS: Record<string, string> = {
  'kích thước': 'Size', 'chất liệu': 'Material', 'màu': 'Colour', 'màu sắc': 'Colour', 'khung': 'Frame', 'mã tham khảo': 'Reference code', 'loại': 'Type', 'hoàn thiện': 'Finish', 'lớp mạ': 'Plating', 'cánh cửa': 'Door leaf',
  'khuôn cửa đơn': 'Single door frame', 'khung cửa': 'Door frame', 'nẹp cửa': 'Door trim', 'sơn bề mặt': 'Surface paint', 'thương hiệu': 'Brand', 'xuất xứ': 'Origin', 'bảo hành': 'Warranty', 'độ dày': 'Thickness', 'chiều cao': 'Height', 'chiều rộng': 'Width', 'chiều dài': 'Length',
}
