insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R01','R02','R04','R23','R24','R16','R17'])), array['floor'], 'Quy định vận hành Marriott · Văn phòng (Front Office, kế toán, ban điều hành…)','Marriott operating standard · Front Office incl. accounting & executive offices','Floor: Vinyl composite tile.','Sàn: gạch vinyl composite (VCT). (Ghép theo nhóm ''văn phòng''; nếu phòng này dùng mục đích khác thì chỉ tham khảo.)','Marriott BOH Finishes Schedule (minimum)',0 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R01','R02','R04','R23','R24','R16','R17'])), array['wall','base'], 'Quy định vận hành Marriott · Văn phòng (Front Office, kế toán, ban điều hành…)','Marriott operating standard · Front Office incl. accounting & executive offices','Wall: Vinyl wall covering, with resilient base. Paint on plaster in closed storage areas.','Tường: giấy dán tường vinyl, chân tường (len) bằng vật liệu đàn hồi/vinyl. Khu kho kín: sơn trên nền trát. (Ghép theo nhóm ''văn phòng''; nếu phòng này dùng mục đích khác thì chỉ tham khảo.)','Marriott BOH Finishes Schedule (minimum)',1 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R01','R02','R04','R23','R24','R16','R17'])), array['ceiling'], 'Quy định vận hành Marriott · Văn phòng (Front Office, kế toán, ban điều hành…)','Marriott operating standard · Front Office incl. accounting & executive offices','Ceiling: Drop in acoustic ceiling tiles.','Trần: trần thả tấm tiêu âm. (Ghép theo nhóm ''văn phòng''; nếu phòng này dùng mục đích khác thì chỉ tham khảo.)','Marriott BOH Finishes Schedule (minimum)',2 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R03'])), array['floor'], 'Quy định vận hành Marriott · Nhân sự / HR','Marriott operating standard · HR / Personnel','Floor: Vinyl composite tile.','Sàn: gạch vinyl composite (VCT).','Marriott BOH Finishes Schedule (minimum)',3 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R03'])), array['wall','base'], 'Quy định vận hành Marriott · Nhân sự / HR','Marriott operating standard · HR / Personnel','Wall: Vinyl wall covering, with resilient base. Paint on plaster in closed storage areas.','Tường: giấy dán tường vinyl, chân tường (len) bằng vật liệu đàn hồi/vinyl. Khu kho kín: sơn trên nền trát.','Marriott BOH Finishes Schedule (minimum)',4 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R03'])), array['ceiling'], 'Quy định vận hành Marriott · Nhân sự / HR','Marriott operating standard · HR / Personnel','Ceiling: Drop in acoustic ceiling tiles.','Trần: trần thả tấm tiêu âm.','Marriott BOH Finishes Schedule (minimum)',5 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R06','R08','R09'])), array['floor'], 'Quy định vận hành Marriott · Khu tắm & vệ sinh nhân viên','Marriott operating standard · Locker rooms – showers & toilets','Floor: Ceramic tile.','Sàn: gạch ceramic.','Marriott BOH Finishes Schedule (minimum)',6 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R06','R08','R09'])), array['wall','base'], 'Quy định vận hành Marriott · Khu tắm & vệ sinh nhân viên','Marriott operating standard · Locker rooms – showers & toilets','Wall: Ceramic tile wall and base.','Tường: ốp gạch ceramic, chân tường cũng bằng gạch ceramic.','Marriott BOH Finishes Schedule (minimum)',7 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R06','R08','R09'])), array['ceiling'], 'Quy định vận hành Marriott · Khu tắm & vệ sinh nhân viên','Marriott operating standard · Locker rooms – showers & toilets','Ceiling: Painted water proof gypsum ceiling.','Trần: trần thạch cao chống ẩm/chống thấm, sơn hoàn thiện.','Marriott BOH Finishes Schedule (minimum)',8 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R08','R09'])), array['floor'], 'Quy định vận hành Marriott · Khu tủ locker & thay đồ','Marriott operating standard · Locker rooms – locker & changing','Floor: Vinyl composite tile.','Sàn: gạch vinyl composite (VCT). (Áp dụng cho khu tủ & thay đồ, không phải khu tắm.)','Marriott BOH Finishes Schedule (minimum)',9 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R08','R09'])), array['wall','base'], 'Quy định vận hành Marriott · Khu tủ locker & thay đồ','Marriott operating standard · Locker rooms – locker & changing','Wall: Epoxy painted with rubber skirting.','Tường: sơn epoxy, len chân tường bằng cao su. (Áp dụng cho khu tủ & thay đồ.)','Marriott BOH Finishes Schedule (minimum)',10 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R08','R09'])), array['ceiling'], 'Quy định vận hành Marriott · Khu tủ locker & thay đồ','Marriott operating standard · Locker rooms – locker & changing','Ceiling: Drop in acoustic ceiling tile.','Trần: trần thả tấm tiêu âm. (Áp dụng cho khu tủ & thay đồ.)','Marriott BOH Finishes Schedule (minimum)',11 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R07'])), array['floor'], 'Quy định vận hành Marriott · Nhà ăn nhân viên','Marriott operating standard · Associate Canteen','Floor: Vinyl composite tile.','Sàn: gạch vinyl composite (VCT).','Marriott BOH Finishes Schedule (minimum)',12 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R07'])), array['wall','base'], 'Quy định vận hành Marriott · Nhà ăn nhân viên','Marriott operating standard · Associate Canteen','Wall: Vinyl wall covering, with resilient base.','Tường: giấy dán tường vinyl, chân tường bằng vật liệu đàn hồi.','Marriott BOH Finishes Schedule (minimum)',13 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R07'])), array['ceiling'], 'Quy định vận hành Marriott · Nhà ăn nhân viên','Marriott operating standard · Associate Canteen','Ceiling: Drop in acoustic ceiling tiles.','Trần: trần thả tấm tiêu âm.','Marriott BOH Finishes Schedule (minimum)',14 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R10'])), array['floor'], 'Quy định vận hành Marriott · Kho hàng khô (kho chung)','Marriott operating standard · General Store (Dry Goods)','Floor: Same as Kitchen areas or sealed concrete.','Sàn: giống khu bếp (xem quy định gạch sàn bếp & kho thực phẩm) hoặc bê tông đánh bóng/phủ chống thấm (sealed concrete).','Marriott BOH Finishes Schedule (minimum)',15 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R10'])), array['wall','base'], 'Quy định vận hành Marriott · Kho hàng khô (kho chung)','Marriott operating standard · General Store (Dry Goods)','Wall: Epoxy paint including skirting.','Tường: sơn epoxy, bao gồm cả chân tường (len).','Marriott BOH Finishes Schedule (minimum)',16 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R10'])), array['ceiling'], 'Quy định vận hành Marriott · Kho hàng khô (kho chung)','Marriott operating standard · General Store (Dry Goods)','Ceiling: Drop in acoustic ceiling tile on corrosion resistant grid and supports.','Trần: trần thả tấm tiêu âm trên khung xương và ty treo chống ăn mòn.','Marriott BOH Finishes Schedule (minimum)',17 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R11'])), array['floor'], 'Quy định vận hành Marriott · Buồng phòng (HSKP)','Marriott operating standard · Housekeeping','Floor: Sealed concrete.','Sàn: bê tông phủ chống thấm/đánh bóng (sealed concrete). (Khu văn phòng buồng phòng: gạch vinyl composite.)','Marriott BOH Finishes Schedule (minimum)',18 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R11'])), array['wall','base'], 'Quy định vận hành Marriott · Buồng phòng (HSKP)','Marriott operating standard · Housekeeping','Wall: Epoxy paint including skirting. (Housekeeping offices: Epoxy paint with vinyl skirting.)','Tường: sơn epoxy gồm cả chân tường. (Văn phòng buồng phòng: sơn epoxy, len chân tường bằng vinyl.)','Marriott BOH Finishes Schedule (minimum)',19 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R11'])), array['ceiling'], 'Quy định vận hành Marriott · Buồng phòng (HSKP)','Marriott operating standard · Housekeeping','Ceiling: Drop in acoustic ceiling tile.','Trần: trần thả tấm tiêu âm.','Marriott BOH Finishes Schedule (minimum)',20 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R12','R13'])), array['floor'], 'Quy định vận hành Marriott · Giặt là (phân loại, giặt, sấy, ủi, gấp và kho vải sạch)','Marriott operating standard · Laundry (sorting, washing, drying, ironing, folding and clean storage)','Floor: Sealed colored concrete, vinyl in office areas.','Sàn: bê tông màu phủ chống thấm (sealed colored concrete); khu văn phòng dùng vinyl.','Marriott BOH Finishes Schedule (minimum)',21 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R12','R13'])), array['wall','base'], 'Quy định vận hành Marriott · Giặt là (phân loại, giặt, sấy, ủi, gấp và kho vải sạch)','Marriott operating standard · Laundry (sorting, washing, drying, ironing, folding and clean storage)','Wall: Epoxy paint including skirting.','Tường: sơn epoxy gồm cả chân tường.','Marriott BOH Finishes Schedule (minimum)',22 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R12','R13'])), array['ceiling'], 'Quy định vận hành Marriott · Giặt là (phân loại, giặt, sấy, ủi, gấp và kho vải sạch)','Marriott operating standard · Laundry (sorting, washing, drying, ironing, folding and clean storage)','Ceiling: Exposed structure, drop in ceiling in offices.','Trần: để lộ kết cấu (không làm trần); khu văn phòng dùng trần thả.','Marriott BOH Finishes Schedule (minimum)',23 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R14'])), array['floor'], 'Quy định vận hành Marriott · Phòng đồng phục','Marriott operating standard · Uniform Issue','Floor: Sealed concrete.','Sàn: bê tông phủ chống thấm/đánh bóng (sealed concrete).','Marriott BOH Finishes Schedule (minimum)',24 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R14'])), array['wall','base'], 'Quy định vận hành Marriott · Phòng đồng phục','Marriott operating standard · Uniform Issue','Wall: Epoxy paint including skirting.','Tường: sơn epoxy gồm cả chân tường.','Marriott BOH Finishes Schedule (minimum)',25 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R14'])), array['ceiling'], 'Quy định vận hành Marriott · Phòng đồng phục','Marriott operating standard · Uniform Issue','Ceiling: Exposed structure.','Trần: để lộ kết cấu (không làm trần).','Marriott BOH Finishes Schedule (minimum)',26 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R15','R21'])), array['floor'], 'Quy định vận hành Marriott · Hành lang dịch vụ','Marriott operating standard · Service Corridors','Floor: Epoxy floor finish.','Sàn: hoàn thiện bằng sơn/lớp phủ epoxy.','Marriott BOH Finishes Schedule (minimum)',27 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R15','R21'])), array['wall','base'], 'Quy định vận hành Marriott · Hành lang dịch vụ','Marriott operating standard · Service Corridors','Wall: Epoxy paint including skirting plus protection rails and corner protection.','Tường: sơn epoxy gồm cả chân tường, kèm thanh chắn bảo vệ tường (protection rails) và nẹp bảo vệ góc.','Marriott BOH Finishes Schedule (minimum)',28 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R15','R21'])), array['ceiling'], 'Quy định vận hành Marriott · Hành lang dịch vụ','Marriott operating standard · Service Corridors','Ceiling: No ceiling is required. Or drop in ceiling.','Trần: không bắt buộc làm trần; hoặc dùng trần thả.','Marriott BOH Finishes Schedule (minimum)',29 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R20','R22'])), array['floor'], 'Quy định vận hành Marriott · Sảnh thang dịch vụ','Marriott operating standard · Service lift Lobbies','Floor: Epoxy floor finish.','Sàn: hoàn thiện bằng sơn/lớp phủ epoxy.','Marriott BOH Finishes Schedule (minimum)',30 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R20','R22'])), array['wall','base'], 'Quy định vận hành Marriott · Sảnh thang dịch vụ','Marriott operating standard · Service lift Lobbies','Wall: Epoxy paint including skirting plus protection rails and corner protection.','Tường: sơn epoxy gồm cả chân tường, kèm thanh chắn bảo vệ tường và nẹp bảo vệ góc.','Marriott BOH Finishes Schedule (minimum)',31 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R20','R22'])), array['ceiling'], 'Quy định vận hành Marriott · Sảnh thang dịch vụ','Marriott operating standard · Service lift Lobbies','Ceiling: Drop in acoustic tile.','Trần: trần thả tấm tiêu âm.','Marriott BOH Finishes Schedule (minimum)',32 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R18'])), array['floor','wall','base','ceiling'], 'Quy định vận hành Marriott · Phòng máy tính / máy chủ','Marriott operating standard · Computing and server rooms','Note that Computing and server rooms have special requirements for finishes – refer to IR spec.','Lưu ý: phòng máy tính và phòng máy chủ có yêu cầu hoàn thiện riêng – xem tài liệu IR spec của Marriott. (Phòng CNTT: kiểm tra xem có phải phòng máy chủ không.)','Marriott BOH Finishes Schedule (minimum)',33 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R19'])), array['floor'], 'Quy định vận hành Marriott · Khu pantry / sơ chế thực phẩm (bếp)','Marriott operating standard · Food Service Pantries','Floor: Minimum slip resistance of 0.6 wet/dry (level floor) and 0.8 wet/dry (ramps). Either: a. Seamless floor: Duraflex or E&A. b. Paver tile, 150 x 150 vitreous with sanded epoxy grout. Coved skirting tile. Note: Marriott to approve floor finish.','Sàn: độ chống trơn tối thiểu 0,6 khi ướt/khô (sàn phẳng) và 0,8 khi ướt/khô (dốc). Chọn một trong hai: a. sàn liền mạch Duraflex hoặc E&A; b. gạch lát (paver) 150 x 150 loại vitreous (độ hút nước rất thấp) với keo chà ron epoxy có cát. Len chân tường dạng gạch bo cong (coved). Lưu ý: Marriott phải duyệt vật liệu sàn.','Marriott BOH Finishes Schedule (minimum)',34 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R19'])), array['wall','base'], 'Quy định vận hành Marriott · Khu pantry / sơ chế thực phẩm (bếp)','Marriott operating standard · Food Service Pantries','Wall: Ceramic tile with skirting same material as floor. Note: Marriott to approve floor finish.','Tường: ốp gạch ceramic, len chân tường cùng vật liệu với sàn. Lưu ý: Marriott phải duyệt.','Marriott BOH Finishes Schedule (minimum)',35 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R19'])), array['ceiling'], 'Quy định vận hành Marriott · Khu pantry / sơ chế thực phẩm (bếp)','Marriott operating standard · Food Service Pantries','Ceiling: A fire rated (to local codes) and accessible, washable, non-corroding (tile and support) with recessed lighting. Submit specifications to MII for approval. Note: Marriott to approve floor finish.','Trần: chống cháy (theo quy chuẩn địa phương), có thể mở để kiểm tra, rửa được, không ăn mòn (cả tấm và khung đỡ), đèn âm trần. Nộp thông số kỹ thuật cho MII (Marriott International) để duyệt. Lưu ý: Marriott phải duyệt.','Marriott BOH Finishes Schedule (minimum)',36 from public.projects p where p.name='BOH Westin Kim Mã';
insert into public.project_rules(project_id,room_ids,elements,title_vn,title_en,body_en,body_vn,source,sort)
select p.id, array(select r.id from public.rooms r where r.project_id=p.id and r.code = any(array['R19','R10'])), array['floor'], 'Quy định vận hành Marriott · Gạch sàn bếp & kho thực phẩm','Marriott operating standard · Food & Beverage Storage and Kitchen Floor Tiles','Hotel kitchen floor tiles to be acid resistant, heavy duty ceramic tiles manufactured to provide chemical and wear resistant floors for commercial kitchens.
• Chemical resistant: resistant to most acids (except hydrofluoric), alkalis, solvents, oils, fats and cleaning solutions. Water absorption less than 3%.
• Hygienic: good resistance to penetration of greases, fats and other food waste. Easy to clean. Matching coved skirting piece available for use at floor/wall junction.
• Safety: minimum slip resistance of 0.6 wet/dry for level floors and 0.8 wet/dry for ramps (equivalent to R12 / R13).
• Durable: installation to comply with ANSI A118.5. Epoxy grout must be used.
• Physical description: 150 x 150 mm, 12 mm minimum thickness, grey colour.','Gạch sàn bếp khách sạn phải chịu axit, là gạch ceramic công nghiệp chịu tải nặng, chịu hóa chất và mài mòn cho bếp thương mại.
• Kháng hóa chất: chịu hầu hết axit (trừ axit flohydric), kiềm, dung môi, dầu mỡ và chất tẩy rửa. Độ hút nước dưới 3%.
• Vệ sinh: chống thấm mỡ, dầu và thức ăn thừa, dễ lau chùi. Có sẵn len chân tường dạng cong đồng bộ ở chỗ giáp sàn – tường.
• An toàn: độ chống trơn tối thiểu 0,6 khi ướt/khô cho sàn phẳng và 0,8 cho dốc (tương đương R12 / R13).
• Bền: thi công theo tiêu chuẩn ANSI A118.5. Bắt buộc dùng keo chà ron epoxy.
• Quy cách: 150 x 150 mm, dày tối thiểu 12 mm, màu xám.','Marriott – Food and Beverage Storage and Kitchen Floor Tiles',37 from public.projects p where p.name='BOH Westin Kim Mã';